# Generated by Django 4.1.6 on 2023-12-13 13:04

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название продукта')),
                ('short_description', models.TextField(max_length=200, verbose_name='Краткое описание продукта')),
                ('full_description', models.TextField(verbose_name='Полное описание продукта')),
                ('quantity', models.PositiveSmallIntegerField(default=10, verbose_name='Кол-во')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('sku', models.CharField(max_length=50, verbose_name='Артикул')),
                ('preview', models.ImageField(upload_to=store.models.Product.make_preview_path, verbose_name='Заставка')),
                ('condition', models.CharField(choices=[(None, ''), ('new', 'new'), ('sale', 'sale'), ('sold', 'sold')], max_length=10, verbose_name='Состояние')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Категория')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Продукт')),
            ],
        ),
    ]
