# Generated by Django 4.1.6 on 2023-12-13 13:07

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=store.models.ProductImage.make_image_path, verbose_name='Фото'),
        ),
    ]
