# Generated by Django 4.1.6 on 2023-12-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[(None, ''), ('new', 'new'), ('sale', 'sale'), ('sold', 'sold')], max_length=10, verbose_name='Состояние'),
        ),
    ]
